/**
 * OpenCode Plugin Auto-Installer
 * 
 * Automatically installs a notification plugin to ~/.config/opencode/plugins/
 * on first orchestrator startup. The plugin sends OSC 777 notifications when
 * OpenCode sessions complete or need user attention.
 */

import fs from 'fs'
import path from 'path'
import os from 'os'

const OPENCODE_CONFIG_DIR = path.join(os.homedir(), '.config', 'opencode')
const OPENCODE_PLUGINS_DIR = path.join(OPENCODE_CONFIG_DIR, 'plugins')
const PLUGIN_FILE = 'orchestrator-notify.js'

// Plugin content - sends OSC 777 notifications on key events
const PLUGIN_CONTENT = `// Auto-generated by Terminal Orchestrator
// Sends OSC notifications when OpenCode sessions complete

export const OrchestratorNotifyPlugin = async () => {
  return {
    event: async ({ event }) => {
      // Session done, agent waiting for input
      if (event.type === "session.idle") {
        process.stdout.write('\\x1b]777;notify;OpenCode;Session Complete\\x07')
      }
      // Permission dialog appeared - needs user action
      if (event.type === "permission.asked") {
        process.stdout.write('\\x1b]777;notify;OpenCode;Permission Required\\x07')
      }
      // Error occurred
      if (event.type === "session.error") {
        process.stdout.write('\\x1b]777;notify;OpenCode;Error Occurred\\x07')
      }
    },
  }
}
`

// Track installation state to avoid repeated checks
let installed = false
let checked = false

/**
 * Ensures the OpenCode notification plugin is installed.
 * Creates the plugin directory if needed and writes the plugin file.
 * 
 * @returns true if plugin was newly installed, false if already existed or failed
 */
export function ensureOpenCodePlugin(): boolean {
  // Skip if already checked this session
  if (checked) return false
  checked = true
  
  try {
    // Ensure directories exist
    if (!fs.existsSync(OPENCODE_PLUGINS_DIR)) {
      fs.mkdirSync(OPENCODE_PLUGINS_DIR, { recursive: true })
      console.log('[OpenCode] Created plugins directory:', OPENCODE_PLUGINS_DIR)
    }
    
    const pluginPath = path.join(OPENCODE_PLUGINS_DIR, PLUGIN_FILE)
    
    // Check if already installed
    if (fs.existsSync(pluginPath)) {
      console.log('[OpenCode] Notification plugin already installed')
      installed = true
      return false
    }
    
    // Write plugin
    fs.writeFileSync(pluginPath, PLUGIN_CONTENT, 'utf-8')
    console.log('[OpenCode] Installed notification plugin to:', pluginPath)
    installed = true
    return true
  } catch (error) {
    console.error('[OpenCode] Failed to install notification plugin:', error)
    return false
  }
}

/**
 * Check if the plugin is currently installed.
 */
export function isPluginInstalled(): boolean {
  const pluginPath = path.join(OPENCODE_PLUGINS_DIR, PLUGIN_FILE)
  return fs.existsSync(pluginPath)
}

/**
 * Remove the notification plugin (for uninstall/cleanup).
 */
export function uninstallOpenCodePlugin(): boolean {
  try {
    const pluginPath = path.join(OPENCODE_PLUGINS_DIR, PLUGIN_FILE)
    if (fs.existsSync(pluginPath)) {
      fs.unlinkSync(pluginPath)
      console.log('[OpenCode] Removed notification plugin')
      installed = false
      checked = false
      return true
    }
    return false
  } catch (error) {
    console.error('[OpenCode] Failed to uninstall notification plugin:', error)
    return false
  }
}
